"""initial schema — provenance, ward, observation, wsi, forecast, intervention

Revision ID: 20260917_0001
Revises:
Create Date: 2026-09-17

Hand-written, not autogenerated: this repo has no live Postgres to diff
against at authoring time. Table/column/constraint shapes mirror app/models/
exactly. Once you run this against a real database, prefer
`alembic revision --autogenerate` for every subsequent migration and use this
file only as the shape to diff against on the first run.
"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260917_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _uuid_pk() -> sa.Column:
    return sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True)


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    ]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ---- Provenance --------------------------------------------------
    op.create_table(
        "data_source",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("publisher", sa.String(200), nullable=False),
        sa.Column("url", sa.String(500)),
        sa.Column("licence", sa.String(200)),
        sa.Column("access_tier", sa.String(20), nullable=False),
        sa.Column("notes", sa.Text),
        sa.CheckConstraint(
            "access_tier IN ('public','authorized','synthetic')",
            name="ck_data_source_access_tier",
        ),
    )

    op.create_table(
        "variable_definition",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("code", sa.String(80), nullable=False, unique=True),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("category", sa.String(20), nullable=False),
        sa.Column("unit", sa.String(40)),
        sa.Column("direction", sa.String(20), nullable=False),
        sa.Column("required_resolution", sa.String(20), nullable=False),
        sa.Column("description", sa.Text),
        sa.CheckConstraint(
            "direction IN ('stress_increasing','stress_decreasing')",
            name="ck_variable_direction",
        ),
        sa.CheckConstraint(
            "category IN ('consumption','groundwater','rainfall','supply','loss',"
            "'demographic','spatial','index','forecast','other')",
            name="ck_variable_category",
        ),
        sa.CheckConstraint(
            "required_resolution IN ('ward','dma','node','station','city')",
            name="ck_variable_required_resolution",
        ),
    )

    op.create_table(
        "synthetic_recipe",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("generator_name", sa.String(120), nullable=False),
        sa.Column("generator_version", sa.String(40), nullable=False),
        sa.Column("params", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("seed", sa.Integer),
        sa.Column("rationale", sa.Text, nullable=False),
    )

    op.create_table(
        "availability_assessment",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "variable_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("variable_definition.id"),
            nullable=False,
        ),
        sa.Column("spatial_level", sa.String(20), nullable=False),
        sa.Column("grade", sa.String(1), nullable=False),
        sa.Column("limitation_note", sa.Text, nullable=False),
        sa.Column("assessed_on", sa.String(20)),
        sa.CheckConstraint("grade IN ('A','B','C','D','E')", name="ck_availability_grade"),
        sa.CheckConstraint(
            "spatial_level IN ('ward','dma','node','station','city')",
            name="ck_availability_spatial_level",
        ),
    )

    op.create_table(
        "dataset_version",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "data_source_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("data_source.id"), nullable=False
        ),
        sa.Column(
            "variable_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("variable_definition.id"),
            nullable=False,
        ),
        sa.Column("version_label", sa.String(60), nullable=False),
        sa.Column("spatial_resolution", sa.String(20), nullable=False),
        sa.Column("temporal_resolution", sa.String(40)),
        sa.Column("grade", sa.String(1), nullable=False),
        sa.Column("is_synthetic", sa.Boolean, nullable=False),
        sa.Column(
            "synthetic_recipe_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("synthetic_recipe.id")
        ),
        sa.Column("row_count", sa.Integer),
        sa.Column("content_hash", sa.String(64)),
        sa.CheckConstraint("grade IN ('A','B','C','D','E')", name="ck_dataset_version_grade"),
    )

    op.create_table(
        "ingestion_run",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "dataset_version_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("dataset_version.id"),
            nullable=False,
        ),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("records_in", sa.Integer),
        sa.Column("records_rejected", sa.Integer),
        sa.Column("error_log", postgresql.JSONB),
    )

    # ---- Spatial -------------------------------------------------------
    op.create_table(
        "ward",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("ward_code", sa.String(20), nullable=False, unique=True),
        sa.Column("name", sa.String(200)),
        sa.Column("scheme_year", sa.Integer),
        sa.Column("is_schematic", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("zone", sa.String(20)),
        sa.Column(
            "geom",
            geoalchemy2.Geometry(geometry_type="MULTIPOLYGON", srid=4326),
            nullable=False,
        ),
        sa.Column("population", sa.Integer),
        sa.Column("connections", sa.Integer),
    )
    op.create_index(
        "ix_ward_geom", "ward", ["geom"], unique=False, postgresql_using="gist"
    )

    # ---- Observation -----------------------------------------------------
    op.create_table(
        "observation",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "variable_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("variable_definition.id"),
            nullable=False,
        ),
        sa.Column(
            "dataset_version_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("dataset_version.id"),
            nullable=False,
        ),
        sa.Column("spatial_unit_type", sa.String(20), nullable=False),
        sa.Column("spatial_unit_id", postgresql.UUID(as_uuid=True)),
        sa.Column("period_start", sa.Date, nullable=False),
        sa.Column("period_end", sa.Date, nullable=False),
        sa.Column("value", sa.Numeric(14, 4), nullable=False),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=False),
        sa.Column("is_imputed", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("imputation_method", sa.String(60)),
        sa.CheckConstraint(
            "spatial_unit_type IN ('ward','dma','node','station','city')",
            name="ck_observation_spatial_unit_type",
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_observation_confidence_range"
        ),
    )
    op.create_index(
        "ix_observation_lookup",
        "observation",
        ["variable_id", "spatial_unit_type", "spatial_unit_id", "period_start"],
    )

    # ---- WSI ---------------------------------------------------------
    op.create_table(
        "wsi_config",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("weighting_method", sa.String(20), nullable=False),
        sa.Column("indicator_set", postgresql.JSONB, nullable=False),
        sa.Column("missing_policy", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("min_confidence_threshold", sa.Numeric(4, 3)),
        sa.Column("created_by", sa.String(120)),
        sa.CheckConstraint(
            "weighting_method IN ('entropy','equal','custom')", name="ck_wsi_config_method"
        ),
    )

    op.create_table(
        "wsi_run",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "wsi_config_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("wsi_config.id"), nullable=False
        ),
        sa.Column("period_start", sa.Date, nullable=False),
        sa.Column("period_end", sa.Date, nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.Column("input_dataset_version_ids", postgresql.ARRAY(postgresql.UUID(as_uuid=True))),
        sa.Column("code_version", sa.String(40)),
        sa.Column("content_hash", sa.String(64)),
        sa.Column("computed_weights", postgresql.JSONB),
        sa.CheckConstraint(
            "status IN ('pending','running','succeeded','failed')", name="ck_wsi_run_status"
        ),
    )

    op.create_table(
        "wsi_indicator_value",
        _uuid_pk(),
        sa.Column(
            "wsi_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("wsi_run.id"), nullable=False
        ),
        sa.Column("ward_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ward.id"), nullable=False),
        sa.Column(
            "variable_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("variable_definition.id"),
            nullable=False,
        ),
        sa.Column("raw_value", sa.Numeric(14, 4)),
        sa.Column("normalized_value", sa.Numeric(6, 5)),
        sa.Column("weight_applied", sa.Numeric(6, 5)),
        sa.Column("confidence", sa.Numeric(4, 3)),
        sa.Column("was_imputed", sa.Boolean, nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_wsi_indicator_value_run", "wsi_indicator_value", ["wsi_run_id"])

    op.create_table(
        "wsi_score",
        _uuid_pk(),
        sa.Column(
            "wsi_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("wsi_run.id"), nullable=False
        ),
        sa.Column("ward_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ward.id"), nullable=False),
        sa.Column("score", sa.Numeric(6, 5), nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=False),
        sa.Column("synthetic_share", sa.Numeric(4, 3), nullable=False),
    )
    op.create_index("ix_wsi_score_run", "wsi_score", ["wsi_run_id"])

    # ---- Forecast ------------------------------------------------------
    op.create_table(
        "forecast_model",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("family", sa.String(30), nullable=False),
        sa.Column("hyperparams", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("code_version", sa.String(40)),
        sa.Column("artifact_uri", sa.String(500)),
        sa.CheckConstraint(
            "family IN ('persistence','seasonal_naive','damped_trend','gbdt','lstm')",
            name="ck_forecast_model_family",
        ),
    )

    op.create_table(
        "forecast_run",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "forecast_model_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("forecast_model.id"),
            nullable=False,
        ),
        sa.Column(
            "target_variable_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("variable_definition.id"),
            nullable=False,
        ),
        sa.Column("train_start", sa.Date, nullable=False),
        sa.Column("train_end", sa.Date, nullable=False),
        sa.Column("horizon_periods", sa.Integer, nullable=False),
        sa.Column("validation_scheme", sa.String(20), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("content_hash", sa.String(64)),
        sa.Column("started_at", sa.DateTime(timezone=True)),
        sa.Column("finished_at", sa.DateTime(timezone=True)),
        sa.CheckConstraint(
            "validation_scheme IN ('holdout','rolling_origin')",
            name="ck_forecast_run_validation_scheme",
        ),
    )

    op.create_table(
        "forecast_value",
        _uuid_pk(),
        sa.Column(
            "forecast_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("forecast_run.id"), nullable=False
        ),
        sa.Column("ward_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ward.id"), nullable=False),
        sa.Column("period_start", sa.Date, nullable=False),
        sa.Column("predicted", sa.Numeric(14, 4), nullable=False),
        sa.Column("lower_80", sa.Numeric(14, 4)),
        sa.Column("upper_80", sa.Numeric(14, 4)),
        sa.Column("confidence", sa.Numeric(4, 3)),
    )
    op.create_index("ix_forecast_value_run", "forecast_value", ["forecast_run_id"])

    op.create_table(
        "forecast_metric",
        _uuid_pk(),
        sa.Column(
            "forecast_run_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("forecast_run.id"), nullable=False
        ),
        sa.Column("ward_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("ward.id")),
        sa.Column("fold_index", sa.Integer),
        sa.Column("metric", sa.String(20), nullable=False),
        sa.Column("value", sa.Numeric(14, 6), nullable=False),
        sa.Column("is_baseline", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.CheckConstraint(
            "metric IN ('mae','rmse','mape','stress_class_f1')", name="ck_forecast_metric_name"
        ),
    )
    op.create_index("ix_forecast_metric_run", "forecast_metric", ["forecast_run_id"])

    # ---- Intervention (schema only — Phase 3 writes to these) -----------
    op.create_table(
        "intervention_type",
        _uuid_pk(),
        *_timestamps(),
        sa.Column("code", sa.String(40), nullable=False, unique=True),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("mechanism_description", sa.Text, nullable=False),
        sa.Column("cost_band", sa.String(20), nullable=False),
        sa.Column("applicability_rule", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("equity_note", sa.Text),
        sa.Column("requires_hydraulic_eval", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.CheckConstraint(
            "cost_band IN ('low','low_medium','medium','high')", name="ck_intervention_type_cost_band"
        ),
    )

    op.create_table(
        "intervention_candidate",
        _uuid_pk(),
        *_timestamps(),
        sa.Column(
            "intervention_type_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("intervention_type.id"),
            nullable=False,
        ),
        sa.Column("scope_type", sa.String(20), nullable=False),
        sa.Column("scope_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("est_cost", sa.Numeric(14, 2)),
        sa.Column("cost_confidence", sa.Numeric(4, 3)),
        sa.Column("cost_is_synthetic", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("effect_params", postgresql.JSONB, nullable=False, server_default="{}"),
        sa.Column("effect_confidence", sa.Numeric(4, 3)),
        sa.CheckConstraint(
            "scope_type IN ('ward','dma','node','station','city')",
            name="ck_intervention_candidate_scope_type",
        ),
    )


def downgrade() -> None:
    op.drop_table("intervention_candidate")
    op.drop_table("intervention_type")
    op.drop_table("forecast_metric")
    op.drop_table("forecast_value")
    op.drop_table("forecast_run")
    op.drop_table("forecast_model")
    op.drop_table("wsi_score")
    op.drop_table("wsi_indicator_value")
    op.drop_table("wsi_run")
    op.drop_table("wsi_config")
    op.drop_table("observation")
    op.drop_index("ix_ward_geom", table_name="ward")
    op.drop_table("ward")
    op.drop_table("ingestion_run")
    op.drop_table("dataset_version")
    op.drop_table("availability_assessment")
    op.drop_table("synthetic_recipe")
    op.drop_table("variable_definition")
    op.drop_table("data_source")
